name: Unit Tests
run-name: ${{ github.actor }} is testing ${{ github.ref }}
on: [push]
jobs:
  UnitTests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Cache library dependencies
        uses: actions/cache@v3
        with:
          path: |
            libyaml/
            lua/
          key: "library-deps-${{ hashFiles('Makefile') }}"

      - name: Build binary
        run: make YL_LDLIBS='-llua -lyaml -lm'

      - name: Run tests
        run: ./test.sh
