name: Unit Tests
run-name: ${{ github.actor }} is testing ${{ github.ref }}
on: [push]
jobs:
  UnitTests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Make dependencies
        run: make -j lua/install libyaml/install

      # - name: Run tests
      #   run: go test -v ./...
