name: Unit Tests
run-name: ${{ github.actor }} is testing ${{ github.ref }}
on: [push]
jobs:
  UnitTests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y libargparse-dev

      - name: Build binary
        run: make

      - name: Run tests
        run: ./test.sh
